### ISSUE TITLE
Can't seem to cook for companions, only give them ingredients to eat

### ISSUE THREAD

**Issue by Agalyon** [Kizby/Clever-Girl#29]
First, I'm sorry if this isn't how you'd prefer this problem be posted but I don't own the game on steam.

I'd like to feed my companion a cooked meal rather than individual ingredients but I can't figure out why I'm not able. The option goes straight to feeding them a single item. I have cooking and I'm standing next to a campfire. I checked the file and it seems like it should work, not sure what I'm doing wrong. Thanks for any help.

**Comment by Kizby** [comment]
I wanted this feature! If I recall correctly, I couldn't figure out a fair way to handle effect expiration, since non-player creatures don't get hungry, and that's usually what makes effects wear off. Do you have an idea of a way to handle that that would feel fair?

**Comment by Agalyon** [comment]
Ahhh sorry, I didn't realize it wasn't implemented. I'm not a coder by any means, but I bet you could set it to the default metabolizing time, and maybe check if the companion has Fasting Way and/or Mind Over Body and just multiply it if they do rather than using hunger at all.

Or just give it a flat value if its hard to implement, honestly just having the option to feed them an actual meal at all would be so useful. Thanks for the amazing mod, its an absolute must have!

**Comment by Kizby** [comment]
@Agalyon I've started work on this (c3d04438c2e477717a8af6d2d4c40b937f7085c3); it looks like the base game implemented expiration of cooking effects on non-player creatures at some point since I last checked, so this is just a matter of the cooking interface and applying the effects.

That commit has support for preset meals and cooking from ingredients if you want to try it out and maybe check for bugs! You can either use a campfire with companions adjacent to you to feed multiple at once, or feed your companion while near a campfire to just feed the one.

**Comment by Kizby** [comment]
The ability to feed companions from campfires using preset meals, known recipes, or specific ingredients is implemented at ea4e5002cd947b013c0b5db54fb9b6bd98da4ede! Again, beta testing from the main branch would be super helpful to check for bugs, but otherwise this is probably going out to mainline soon and I'll expect the bugs to be reported there lol
